version: "3"

services: # 이 항목 밑에 실행하려는 컨테이너들 정의

  mariadb: # 서비스의 이름
    container_name: mariadb
    env_file: .env
    build:
      context: requirements/mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$DB_ROOT_PASSWORD"]
      interval: 1s
      timeout: 2s
      retries: 20
      start_period: 7s
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    restart: always
    env_file: .env
    build:
      context: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www
    networks:
      - inception-network
    depends_on:
      mariadb:
        condition: service_healthy   

  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
    networks:
      - inception-network
    volumes:
      - wordpress_volume:/var/www
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443

networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  db_volume:
    driver: local
    # driver_opts:
      # device: ${INCEPTION_PATH}/db
      # type: 'none'
      # o: 'bind'

  wordpress_volume:
    driver: local
    # driver_opts:
      # device: ${INCEPTION_PATH}/wordpress
      # type: 'none'
      # o: 'bind'
